### ISSUE TITLE
Wormhole

### ISSUE THREAD

**Issue by VForiel** [Gunivers/Altcord#1]
Allow to connect 2 text channels (even on two different discords).

Wormhole are virtual channels that can be created anywhere and that is associated it's admins (ie. creator)

Then, the admins have to connect channels to this wormhole. Once it's done, messages sent on the conencted channel will be send on the other channels connected to this wormhole.

- [ ] Allow to configure the name and avatar of wormhole travelers
- [ ] Allow to set direction of the wormhole for each channel (send only, recieve only or send and recieve)
- [ ] Allow replies, message edition and deletion
- [ ] Allow to create wormhole rules, accessible though command `/wh rules` that will diplay rules for all wormholes connected to the channel
- [ ] Allow to created automoderation rules that will prevent stop wormhole travelers if the content of the message is in violation to these rules. The automod can also ban a user from a wormhole
- [ ] If a user is ban on a server connected to a wormhole, he can't use any channel connected to this wormhole.

**Comment by ascpial** [comment]
Will not be implemented in the core, this will be done by a plugin.
Also creating an alias for slash commands is a very bad idea, considering the limited amount of commands available.
